### ISSUE TITLE
Auto WalkDriveFly Does Not Stop with Ctrl+F9

### ISSUE THREAD

**Issue by olwince** [LeoTN/gtav-tweaks#20] opened 2024-09-19 04:46 UTC
### Duplicate Request?

- [X] This request is unique.

### Operating System

Windows 10 22H2

### Software Version

0.3.0

### Issue Type

- [ ] Crash
- [ ] Warning Message
- [x] Other Issue

### Action(s) Leading To The Issue

Pressing Ctrl+F9 does not disable holding w. Manually clicking Pause Script in tray icon seems to be the only way I could disable the macro.

Update: Actually Alt-Tab to switch active window is what disables the script for me. Just Alt-Tab to any window (with GTA in windowed mode), without clicking Pause Script in the tray icon, and then Alt-Tab back into game - the script is stopped.

**Comment by LeoTN** [comment] 2024-09-21 13:58
Hi, thank you for your reported issue! Yeah, you're right with tabbing out of GTA V. This hotkey will only work when GTA V is the active window. I implemented this as a safety measure to avoid accidental inputs outside the game.

But I still don't know why pressing the hotkey again wouldn't stop the macro from playing. Could you please update the script to the latest beta version and see if the issue persists? You can do that by checking the beta checkbox in the main window or download it manually from the repo page.

How do you think about this tool in general? Any thoughts on how to improve the tutorial or things you might find annoying or that you would change?

**Comment by olwince** [comment] 2024-09-22 04:41
Thanks for your response! I have tried v0.3.1-beta and I have the same problem. Here is what I found:

1. When in GTA 5, I press CTRL-F9 the macro starts, and one instance of AutoHotKey32.exe runs. 
2. When I press the same hotkey again, another instance of AutoHotKey32.exe with a different PID runs. 
3. Pressing the hotkey more times does not end either processes or create new ones. 
4. When I Alt-Tab out of the game and focus on another window, both processes end. 
This occurs in both windowed and fullscreen mode.

In general, I find this tool really useful. I have just started playing GTA V again. The (lack of) dexterity of my left hand is such that holding w for a long time while tapping shift and/or A and D is very straining. This is my primary reason for using this tool. I have tried to write my own script with AHK, but this with it's active window detection is far better than what I can come up with. 

I have not tried the other features such as recording new macro. The Create Solo Lobby macro works perfectly. 

I suspect my problem maybe an isolated case, since presumably it does not happen to you. I am on the brink of reinstalling Windows 10 on my current computer because of some minor but irritating Windows Store app problem which I cannot solve. I also have another computer I can run GTA65 on and test. I will do so within the next week and report back.

**Comment by LeoTN** [comment] 2024-09-22 15:59
Woah, you really did some investigation. I appreciate that :) 

The hotkey basically works like this:

1. When pressing the hotkey, the macro file is started.
2. It checks for any other instance of this macro file already running.
3. If there is one, it will terminate that instance and itself too.
4. Otherwise, it would just hold down W and Numpad5 (if you want to fly a plane AFK).

This allows the macro to be started by pressing the hotkey once and ending it by pressing the hotkey twice.

I could imagine an issue where the macro cannot identify the already running instance and therefore not terminating it. It is using a windows related feature called **_ComObjects_,** as you can see in the code below. Maybe something is "broken" in your windows installation or I need to adjust the search query, who knows.

```
; This block of code makes this hotkey toggelable. It scans for already existing instances of this script and if it
; detects one, it will close both this and the old instance.
processSearchQuery := 'AutoHotkey32.exe" "' . A_ScriptFullPath . '"'
scriptPID := WinGetPID(A_ScriptHwnd)
For (process in ComObjGet("winmgmts:").ExecQuery("Select * from Win32_Process"))
{
    If (InStr(process.CommandLine, processSearchQuery) && process.ProcessID != scriptPID)
    {
        ProcessClose(process.ProcessID)
        ; Only in case the keys are still pressed by the old script.
        Send("{w Up}")
        Send("{Numpad5 Up}")
        ExitApp()
    }
}
```

I tried this hotkey and it works fine on my machine (like every developer would say) 😂
I`m looking forward to hearing from you 😄 

Have a nice day 👋

**Comment by LeoTN** [comment] 2024-11-11 17:38
Hey, I wonder what the results with your clean installed Windows machine are. I might have to fix an issue then :)

**Comment by LeoTN** [comment] 2024-12-18 16:08
I think I'll close this issue now because I could not reproduce it and there is no reply from the person that created it.

**Closed as completed by LeoTN** 2024-12-18 16:08 UTC
Labels: bug
